config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks

  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :to_dos, inverse_of: :task
  accepts_nested_attributes_for :to_dos, allow_destroy: true, reject_if: Proc.new { |attrs| attrs["title"].blank? }

  validates :name, presence: true
  validates :name, length: { maximum: 200 }
end

app/models/to_do.rb
class ToDo < ApplicationRecord
  belongs_to :task, inverse_of: :to_dos
  
  validates :title, presence: true
  validates :title, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include TasksHelper
  
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
    3.times{@task.to_dos.build}
  end

  def create
    @task = Task.new
    @task.assign_attributes(task_params)

    if @task.save
      redirect_to edit_task_path(@task)
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
    @task.to_dos.build
  end

  def update
    @task = Task.find(params[:id])
    @task.assign_attributes(task_params)

    if @task.save
      redirect_to edit_task_path(@task)
    else
      render :edit
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, to_dos_attributes: [:id, :title, :is_done, :_destroy])
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def format_date(time)
    time.strftime("%m/%d/%y %l:%M")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.haml
- @task.errors.full_messages.each do |message| 
  %div
    = message
= form_for(@task) do |form|
  %div
    = form.text_field :name
  %ul
    = form.fields_for :to_dos do |builder|
      %ol
        - if builder.object.created_at
          = "Created at: #{format_date(builder.object.created_at)}"
        = builder.hidden_field :id
        = builder.text_field :title
        | Check if is completed
        = builder.check_box :is_done
        | Check for remove
        = builder.check_box :_destroy

  %div
    = form.submit 

app/views/tasks/_menu.html.haml
%div
  = link_to('List',tasks_path )
  = link_to('New',new_task_path )

app/views/tasks/edit.html.haml
%h1 Edit
= render partial: "menu"
= render partial: "form"

app/views/tasks/index.html.haml
%h1 ToDo List
= render partial: "menu"

%h2 List of tasks
%table
  %tr
    %th{style: "width: 300px"} Name
    %th{style: "width: 300px"} Actions
  - @tasks.each do |task|
    %tr
      %td
        = task.name
      %td
        = link_to("Edit", edit_task_path(task))
        | 
        = link_to("Delete", task_path(task), method: :delete, data: { confirm: "Are you sure?" })

app/views/tasks/new.html.haml
%h1 New Task
= render partial: "menu"
= render partial: "form"

app/views/tasks/show.html.haml
%h1 Show
= render partial: "menu"

%h2= @task.name